export const ANIMAL_CHARACTER: string[] = [
  "Giocoso", "Pigro", "Vivace", "Timido", "Coraggioso", "Protettivo", "Indipendente",
  "Affettuoso", "Testardo", "Obbediente", "Curioso", "Diffidente", "Socievole",
  "Territoriale", "Goloso", "Paziente", "Impulsivo", "Dolce", "Aggressivo", "Calmo",
  "Espansivo", "Riservato", "Fedele", "Ribelle", "Docile", "Vigile", "Sonnolento",
  "Energico", "Schivo", "Possessivo", "Amichevole", "Sospettoso", "Equilibrato",
  "Nervoso", "Rilassato", "Guardiano", "Coccolone", "Selettivo", "Chiassoso",
  "Silenzioso", "Esploratore", "Sedentario", "Atletico", "Goffo", "Elegante",
  "Molto Vocale", "Discreto", "Ansioso", "Sicuro Di Sé", "Adattabile",
];

export const ANIMAL_INTERESTS: string[] = [
  "Inseguire La Palla", "Correre All'Aperto", "Dormire Al Sole", "Nuotare", "Scavare",
  "Annusare Tutto", "Giocare Con Altri Animali", "Guardare Fuori Dalla Finestra",
  "Rincorrere Insetti", "Giocare Con Il Gomitolo", "Masticare Giocattoli", "Fare Le Fusa",
  "Salire In Alto", "Nascondersi In Scatole", "Giocare A Rincorrersi", "Passeggiate Lunghe",
  "Andare In Macchina", "Fiutare Nuovi Odori", "Rotolarsi Nell'Erba", "Cacciare Piccoli Oggetti",
  "Giocare Con L'Acqua", "Osservare Uccelli", "Grattarsi Contro Superfici", "Tira E Molla",
  "Correre Dietro Alla Luce", "Esplorare Nuovi Ambienti", "Dormire Sul Divano",
  "Farsi Spazzolare", "Ricevere Coccole", "Nascondersi Sotto I Mobili", "Cacciare Topi Giocattolo",
  "Interagire Con Bambini", "Salutare Gli Ospiti", "Fare Il Bagno", "Giocare Con Le Foglie",
  "Rosicchiare Ossi", "Arrampicarsi Sui Tiragraffi", "Guardare La Tv", "Ascoltare Musica",
  "Seguire Il Padrone Ovunque", "Dormire In Compagnia", "Fare Capriole", "Giocare Con Le Bolle",
  "Cercare Cibo Nascosto", "Fare Amicizia Con Altri Animali", "Correre In Spiaggia",
  "Fare Escursioni", "Giocare Nella Neve", "Osservare Pesci", "Portare A Spasso Un Giocattolo",
  "Dormire Nella Cesta",
];

export const ANIMAL_HABITS: string[] = [
  "Abbaiare Alla Porta", "Miagolare Al Mattino", "Dormire Tutto Il Giorno",
  "Nascondere Giocattoli", "Grattare I Mobili", "Seguire I Rumori Di Cucina",
  "Dormire Ai Piedi Del Letto", "Aspettare Al Cancello", "Fare Le Fusa Di Notte",
  "Rincorrersi La Coda", "Scodinzolare Sempre", "Nascondersi Quando Suona Il Campanello",
  "Salire Sul Tavolo", "Rubare Cibo Dal Piatto", "Grattarsi L'Orecchio", "Leccarsi Le Zampe",
  "Dormire Nella Cesta", "Guaire Se Lasciato Solo", "Fare I Bisogni Sempre Nello Stesso Posto",
  "Nascondersi Durante I Temporali", "Correre Dopo Il Bagno", "Dormire Con Un Occhio Aperto",
  "Aspettare Il Rientro Alla Porta", "Rosicchiare Le Ciabatte", "Farsi Vedere Solo Per Mangiare",
  "Dormire Sul Termosifone", "Guardare Fuori Dal Balcone Per Ore", "Seguire La Routine Dei Pasti",
  "Dormire Accoccolato", "Far Rumore Con Le Ciotole Vuote", "Grattare Alla Porta Del Bagno",
  "Sonnecchiare Sul Divano Preferito", "Nascondere Ossi Per Dopo", "Miagolare Per Attenzione",
  "Abbaiare Ai Rumori Sconosciuti", "Girare In Tondo Prima Di Sdraiarsi", "Dormire Sotto Le Coperte",
  "Aspettare Vicino Alla Ciotola", "Fare Dispetti Quando Annoiato", "Seguire Ogni Stanza Della Casa",
  "Russare Nel Sonno", "Alzarsi Presto La Mattina", "Reagire Al Suono Del Sacchetto Del Cibo",
  "Grattarsi Contro Lo Stipite", "Fissare Il Vuoto", "Impastare Con Le Zampe",
  "Correre Improvvisamente Senza Motivo", "Nascondersi Dagli Estranei",
  "Dormire Rannicchiato In Un Angolo", "Portare Regali Inaspettati",
];
