export const POSITIVE_INTERACTIONS: string[] = [
  "Le hai fatto una sorpresa",
  "Hai ascoltato i suoi problemi senza giudicare",
  "Avete riso fino alle lacrime insieme",
  "L'hai aiutata in un momento difficile",
  "Le hai fatto un regalo pensato apposta per lei",
  "Hai difeso il suo punto di vista davanti ad altri",
  "Avete cucinato insieme",
  "Le hai scritto solo per dirle che ti mancava",
  "Hai mantenuto un suo segreto",
  "L'hai aiutata a traslocare",
  "Avete fatto una lunga passeggiata parlando di tutto",
  "Le hai dato un consiglio che si è rivelato prezioso",
  "Hai festeggiato un suo successo come fosse tuo",
  "L'hai perdonata senza rancore",
  "Avete guardato un film abbracciati",
  "Le hai prestato dei soldi senza farne un problema",
  "Hai notato che stava male e sei rimasto",
  "Avete riso di una battuta solo vostra",
  "L'hai presentata a persone importanti per te",
  "Hai imparato qualcosa di nuovo insieme a lei",
  "Le hai scritto una lettera sincera",
  "Hai rispettato un suo momento di silenzio",
  "Avete ballato senza motivo in cucina",
  "L'hai sostenuta a un evento importante",
  "Hai condiviso un ricordo che non racconti a tutti",
  "Avete organizzato una sorpresa per qualcun altro insieme",
  "Le hai detto la verità anche se scomoda, con delicatezza",
  "Hai fatto il tifo per lei da lontano",
  "Avete cucinato il piatto preferito dell'altro",
  "L'hai chiamata solo per sentirla, senza motivo",
  "Hai riconosciuto un tuo errore con lei",
  "Avete condiviso una vittoria piccola ma vostra",
  "Le hai portato la colazione a letto",
  "Hai fatto qualcosa di scomodo pur di aiutarla",
  "Avete pianto insieme per qualcosa di bello",
  "L'hai aspettata senza lamentarti",
  "Hai approfondito una sua passione per capirla meglio",
  "Avete fatto un viaggio improvvisato",
  "Le hai scritto qualcosa di dolce senza motivo",
  "Hai difeso la sua reputazione in sua assenza",
  "Avete condiviso un silenzio confortevole",
  "L'hai aiutata a prepararsi per qualcosa di importante",
  "Hai avuto pazienza in un suo momento difficile",
  "Avete riso ricordando una vecchia storia",
  "Le hai fatto un complimento sincero",
  "Hai rinunciato a qualcosa per stare con lei",
  "Avete festeggiato un traguardo con una cena speciale",
  "L'hai sorpresa ricordando un dettaglio piccolo",
  "Hai condiviso una tua paura con lei",
  "Avete costruito qualcosa insieme, anche piccolo",
];

export const NEGATIVE_INTERACTIONS: string[] = [
  "Hai dimenticato un suo appuntamento importante",
  "L'hai criticata davanti ad altri",
  "Hai riso di qualcosa che per lei era serio",
  "Le hai mentito su qualcosa di piccolo",
  "Hai ignorato i suoi messaggi per giorni",
  "Avete litigato per qualcosa di futile",
  "Hai rivelato un suo segreto",
  "L'hai lasciata pagare sempre lei",
  "Hai cancellato un piano all'ultimo momento",
  "Hai fatto un commento tagliente senza pensarci",
  "L'hai fatta aspettare troppo a lungo",
  "Hai preso in giro qualcosa a cui teneva",
  "Hai dimenticato il suo compleanno",
  "Avete avuto un malinteso mai chiarito",
  "L'hai esclusa da un gruppo di amici",
  "Hai minimizzato un suo problema",
  "Hai copiato qualcosa di suo senza dirglielo",
  "Le hai dato un consiglio che si è rivelato dannoso",
  "Hai preferito altri impegni al posto suo",
  "Avete gareggiato per qualcosa nel modo sbagliato",
  "Hai fatto trapelare qualcosa che non dovevi",
  "L'hai giudicata senza conoscere tutta la storia",
  "Hai risposto male senza motivo",
  "Hai rotto una promessa fatta a lei",
  "Avete discusso davanti ad altre persone",
  "Hai paragonato la sua situazione a quella di un altro",
  "Hai preso le distanze in un momento difficile per lei",
  "L'hai messa in imbarazzo senza volerlo ammettere",
  "Hai insistito nonostante il suo no",
  "Avete avuto opinioni opposte su qualcosa di importante",
  "Hai dato per scontato il suo aiuto",
  "Hai reagito con freddezza a una sua buona notizia",
  "Hai dimenticato di ringraziarla",
  "Le hai fatto una domanda scomoda nel momento sbagliato",
  "Hai preferito il tuo orgoglio a una scusa",
  "Avete avuto un silenzio pesante dopo un litigio",
  "Hai sottovalutato quanto ci tenesse",
  "Hai fatto una battuta fuori luogo",
  "Hai interrotto qualcosa di importante per lei",
  "Avete avuto punti di vista incompatibili su una scelta",
  "Hai preso una decisione che la riguardava senza chiederle nulla",
  "Hai sminuito un suo risultato",
  "Hai evitato una conversazione necessaria",
  "Le hai dato ragione solo per chiudere il discorso",
  "Hai fatto un confronto che l'ha ferita",
  "Avete avuto una gelosia mai espressa apertamente",
  "Hai dimenticato una cosa che le avevi promesso",
  "Hai reagito in modo sproporzionato a un piccolo errore",
  "Hai lasciato che un malinteso si trascinasse troppo a lungo",
  "Hai anteposto un like a una chiamata quando serviva davvero",
];

export const ANIMAL_POSITIVE_INTERACTIONS: string[] = [
  "Le hai dato il suo cibo preferito",
  "Avete giocato fino a stancarvi entrambi",
  "L'hai portata a fare una lunga passeggiata",
  "Le hai fatto le coccole per tanto tempo",
  "Hai imparato un suo nuovo trucco insieme a lei",
  "L'hai lasciata dormire sul letto per una notte",
  "Le hai comprato un giocattolo nuovo",
  "Hai notato che stava male e l'hai portata dal veterinario",
  "Avete esplorato un posto nuovo insieme",
  "L'hai spazzolata con calma",
  "Hai organizzato la sua cuccia con più cura",
  "Le hai parlato con dolcezza dopo una giornata difficile",
  "Avete fatto un bagno insieme senza stress",
  "L'hai premiata per essersi comportata bene",
  "Hai passato un intero pomeriggio solo con lei",
  "Le hai preparato uno spuntino speciale",
  "Hai giocato al suo gioco preferito",
  "L'hai presentata a un nuovo amico a quattro zampe",
  "Hai scattato una foto che ti ha fatto sorridere tutto il giorno",
  "L'hai lasciata scegliere lei dove andare a passeggio",
];

export const ANIMAL_NEGATIVE_INTERACTIONS: string[] = [
  "Hai dimenticato il suo pasto in orario",
  "L'hai sgridata più del necessario",
  "Hai rimandato la sua passeggiata troppo a lungo",
  "L'hai lasciata sola più del solito",
  "Hai ignorato un suo segnale di disagio",
  "Hai saltato la sua toelettatura",
  "L'hai portata dal veterinario in ritardo",
  "Hai avuto poca pazienza con lei",
  "Hai cambiato le sue abitudini senza gradualità",
  "L'hai lasciata in un posto rumoroso troppo a lungo",
  "Hai dimenticato di darle acqua fresca",
  "Hai reagito male a un suo dispetto",
  "L'hai confinata in uno spazio troppo piccolo",
  "Hai saltato il suo momento di gioco quotidiano",
  "Hai urlato per uno spavento e l'hai spaventata",
  "L'hai lasciata senza compagnia per un'intera giornata",
  "Hai dimenticato il suo giocattolo preferito a casa",
  "Hai avuto fretta durante la sua passeggiata",
  "L'hai rimproverata senza che capisse il motivo",
  "Hai rimandato una sua visita di controllo",
];
